export type {
  Alternate,
  Author,
  Crawler,
  Favicon,
  General,
  IconLink,
  Metadata,
  MetadataDocument,
  Mobile,
  Opengraph,
  OpengraphImage,
  OpengraphMedia,
  SiteVerification,
  StructuredData,
  StructuredDataIssue,
  ThemeColor,
  TouchIcon,
  Twitter,
  TwitterLabel,
} from './metadata';
